[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.8.0"
polars = "0.26.1"
polars-io = "0.26.1"
polars-ops = "0.26.1"
env_logger = "0.7.1"